name: Bug Report
description: Report a bug
labels: [bug]
assignees: []
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Prerequisites
      description: |
        *If **all** checks are not passed then the issue will be closed.*
      options:
        - label: I have checked that no other similar issue already exists.
          required: true
        - label: I have checked that this issue is actually a bug and not a feature.
          required: true
        - label: I am running the latest release version.
          required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: |
        Operating system name and version.
      placeholder: |
        ex: Windows 10
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: |
        Browser name and version if possible.
      placeholder: |
        ex: Google Chrome, Google Chrome 96
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Extension Version
      description: |
        Release version or branch commit where the issue occured. Do not write 'latest'.
      placeholder: |
        ex: v2, 8266f8b
    validations:
      required: true

  - type: checkboxes
    id: component
    attributes:
      label: Components
      description: |
        Select which components are the wrong color.
      options:
        - label: Pinned issues
          required: false
        - label: Closed issues
          required: false
        - label: Issue timeline
          required: false
        - label: Issues tab
          required: false
        - label: Issue hovercard
          required: false
        - label: Closed pulls
          required: false
        - label: Pull timeline
          required: false
        - label: Pull hovercard
          required: false
        - label: Subscriptions
          required: false
        - label: Search
          required: false
        - label: Projects
          required: false
        - label: Projects (beta)
          required: false
        - label: Insights
          required: false
        - label: Other (please specify)
          required: false

  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: |
        Explain your issue.
    validations:
      required: false